{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nl-portal-backend.fullname" . }}
  labels:
    {{- include "nl-portal-backend.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_CREDENTIALS_SECRET: {{ .Values.settings.keycloak.credentials.secret | toString | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.settings.spring.datasource.password | toString | b64enc | quote }}
  NLPORTAL_ZGW_CATALOGIAPI_SECRET: {{ .Values.settings.nlPortal.zgw.catalogiapi.secret | toString | b64enc | quote }}
  NLPORTAL_ZGW_DOCUMENTAPIS_SECRET: {{ .Values.settings.nlPortal.zgw.documentenapis.configurations.openzaak.secret | toString | b64enc | quote }}
  NLPORTAL_ZGW_ZAKENAPI_SECRET: {{ .Values.settings.nlPortal.zgw.zakenapi.secret | toString | b64enc | quote }}
  NLPORTAL_OBJECTSAPI_TOKEN: {{ .Values.settings.nlPortal.objectsapi.token | toString | b64enc | quote }}
  NLPORTAL_OPENKLANT_SECRET: {{ .Values.settings.nlPortal.openklant.secret | toString | b64enc | quote }}
{{- end }}