---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nl-portal-configpanel-backend.fullname" . }}
  labels:
    {{- include "nl-portal-configpanel-backend.labels" . | nindent 4 }}
data:
  LOGLEVEL: {{ .Values.settings.app.logLevel | quote }}
  DATABASE_URL: {{ .Values.settings.database.url | quote }}
  JWKS_URI: {{ .Values.settings.auth.jwksURI | quote }}
  CONFIG_SERVER_PREFIX: {{ .Values.settings.app.serverPrefix | quote }}
  CONFIG_CACHE_TTL: {{ .Values.settings.app.cacheTTL | quote }}
  CONFIG_NOTIFY_ENABLED: {{ .Values.settings.app.notifyEnabled | quote }}
  CONFIG_NOTIFY_LIST: {{ .Values.settings.app.notifyList | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.settings.app.security.cors.allowedOrigins | quote }}
  CORS_ALLOWED_HEADERS: {{ .Values.settings.app.security.cors.allowedHeaders | quote }}
  CORS_ALLOWED_METHODS: {{ .Values.settings.app.security.cors.allowedMethods | quote }}
