{{- if not .Values.secretEnvVars }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nl-portal-configpanel-backend.fullname" . }}
  labels:
    {{- include "nl-portal-configpanel-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.settings.database.username | quote }}
  DATABASE_PASSWORD: {{ .Values.settings.database.password | quote }}
  CONFIG_SERVER_TOKEN: {{ .Values.settings.app.configServerToken | quote }}
{{- end }}
